boxes/__init__.py
boxes/edges.py
boxes/generators/_template.py
boxes/generators/box.py
boxes/generators/box2.py
boxes/generators/box3.py
boxes/generators/castle.py
boxes/generators/drillbox.py
boxes/generators/flexbox.py
boxes/generators/flexbox2.py
boxes/generators/flexbox3.py
boxes/generators/flexbox4.py
boxes/generators/flextest.py
boxes/generators/folder.py
boxes/generators/lamp.py
boxes/generators/magazinefile.py
boxes/generators/printer.py
boxes/generators/silverwarebox.py
boxes/generators/trayinsert.py
boxes/generators/traylayout.py
boxes/generators/typetray.py
boxes/svgutil.py
scripts/boxes
scripts/boxesserver
setup.py

- Use /usr/bin/env to determine path to python3 instead of a hard-coded
path, so that virtualenv stubs work properly.
- Change package name to 'boxes' ('boxes.py' did not work within
virtualenv).

Fix project for use within virtualenv

---

scripts/boxesserver

Was throwing this error:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\n\\AppData\\Local\\Temp\\tmpw8emq0xq'
see https://stackoverflow.com/questions/34716996/cant-remove-a-file-which-created-by-tempfile-mkstemp-on-windows

Fix tmp file access in windows

---

scripts/boxesserver
static/self.css

Triangles before list items now toggle according to open/closed state of item.
(Also removed some random whitespace, sorry.)

boxesserver: Implemented toggling of list item icon

---

.gitignore

In my environment using python3 in a virtual-environment on Debian GNU/Linux, the .egg-info file does not contain .py, so an extra line in .gitignore is needed
Could be replaced with a pattern like *.egg-info/ but that might be to much :-)

Add boxes.egg-info to gitignore

---

examples/generate.sh

This abstracts over the exact location of the bash binary and makes NixOS people happy.

changed /bin/bash to /usr/bin/env bash

---

boxes/__init__.py

Shouldn't the holeSettings given to rectangularWall be forwarded to the inner hexHolesRectangle call?

forward holesSettings to hexHolesRectangle from within rectangularWall

---

documentation/boxes.1
documentation/boxes.xml
documentation/boxesserver.1
documentation/boxesserver.xml
scripts/boxesserver

Hello, this PR allows one to give an optional parameter to the script boxesserver, in order to use another port than the default 8000.
Additionally, simple manpages have been written for user-space scripts. boxesserver's manpage documents the optional parameter to change the port.

Redefine server port+manpages

---

setup.py

Hello, now the PR is mature.
When setup.py is run inside a packaging routine, one has to define an environment variable named
CURRENTLY_PACKAGING, and a special behaviour is used by setup.py to comply with the
File Hierarchy Standard.
This patch does not modify setup.py's behavior for ordinary builds.

Setup for debian

---

boxes/generators/electronicsbox.py

In the generator file for electronicsbox.py was a typo. it should be d3 instead of d2..

fixed d3 diameter (mounting screw holes)

---

documentation/src/install/macos.rst

see https://pycairo.readthedocs.io/en/latest/getting_started.html

added missing instructions for install cairo on mac

---

boxes/__init__.py

In rectangularHole documentation:
- fixes a typo (rectangula_t_) 
- clarifies the fact that x and y are the center of the rectangle
Thank you !

Clarify rectangularHole x,y parameters (center)

---

boxes/__init__.py
boxes/generators/paintbox.py

The issue was caused by an erroneous variable being passed.
This happened since hexHolesRectangle was expecting a settings object but got a tuple passed.

fixed bug where the option hexpattern=True PaintStorage would cause an error.

---

boxes/generators/agricolainsert.py

Hello,
You were right in #243, this insert was designed for 3mm plywood.
I updated the description to be explicit about it, and I also tried to improve thickness tolerance when possible (the cards tray and the horse meeples tray).
In my thickness of 2.85mm the file generated is pretty much the same than before (except the order of the parts).
Thank you

AgricolaInsert: better thickness range support

---

boxes/generators/roundedbox.py

The FlexSettings to controll the flexible corner designs was added to the generator of `roundedbox.py`
Motivation: 
- My printed layout failed because of the very tiny structure. Now I am able to design it slightly more robust very easily.
- The change only needed a very small adaption of the original file.

RoundedBox: Implementation of FlexSettings

---

boxes/generators/dividertray.py

#274 was about two things: a misunderstanding, and a real bug.
This PR fixes the bug :-)
(the reporter closed the issue, I can't reopent it)

Fix DividerTray length with 'outside=false'

---

boxes/generators/atreus21.py
boxes/generators/keyboard.py
boxes/generators/keypad.py

I'm planning to update [my custom keyboard](https://github.com/gcollic/grimoire60_keyboard). I'm doing some test, and obviously I'm using boxes.py this time.
My keyboard is not ready to share, but in preparation I already updated the `atreus21` and `keypad` "boxes" for better reuse, uniformity, and options.
I did the following changes:
- there was duplication
- I created a Keyboard class to share keyboard specific functionnalities
- keypad profits from the code structure of atreus
- `atreus`'s layout was not configurable (but the code was already parameterized), and `keypad`'s layout options were very limited
- I created a unified arg parser (inspired by `argparseSections`)
- the default value gives the same result as before
- both boxes can now generate a lot of different layouts
- the …

Keyboards: refactor common code and add options for atreus and keypad

---

documentation/src/api_navigation.rst

The code example for Boxes.saved_context() uses a with statement
that does not properly call the self.saved_context method (misses
call parenthesis).

Fix Boxes.saved_context example in Navigation documentation

---

boxes/Color.py
boxes/__init__.py
boxes/generators/drillbox.py
documentation/src/usermanual.rst

Adds the parameters: sx, xy, h, holes, firsthole and holeincrement.
It adds two TODOs: 
One needs changes in the Boxes-class and should be in a separate pull request (changing color of the etched boxes) and one that i have not worked out how to do yet (dynamic text). I could try to include them here if you want.
My editor tends to use [black](https://black.readthedocs.io/en/stable/index.html)  to format the code as default and since I could not find any preference for what codestyle to use I kept it on all changed lines (which is more or less everything :-). If you prefer any other style, just say and I will create a new patch in that style.

Parametrizise the drillbox

---

documentation/src/install/macos.rst

When installing Inkscape and the boxes.py extensions on macOS BigSur 11.6 using the procedure described in the documentation I encountered an error : 
`Error: Unknown command: cask`.
After a bit of research, it appears that `cask` is no longer needed to use brew, and `brew install inkscape` is now the way to go, and Inkscape got installed indeed.
Try installing Inkscape with `brew cask install inkscape` as per the documentation.
Use `brew install inkscape` instead
The Homebrew discussion on its Github repo from which I gathered the information : https://github.com/Homebrew/discussions/discussions/902

cask is no longer a brew command

---

boxes/generators/dividertray.py

The new features on the DividerTray are great, thank you ^^
There is now a play for easier divider insertion and removal, but in my case the lack of play was intentional and can help structural integrity with longer box insert made from more flexible wood (the dividers are rarely moved), so I propose to make the play optionnal.

feat: DividerTray make the play optional

---

boxes/drawing.py

Found an error which broke lbrn2 output.
In function _faster_edges(self, inner_corners)_ the duplicate removal fails if there is only one element in the path list. This single element gets removed in any case, which results in an empty path list, which in turn will crash the lbrn2 output.
Furthermore trying to output an empty list via print also results in an error which costs me some time at debugging...
This patch deals with both issues.
Cheers
Klaus

fixed error generating an empty path list

---

scripts/boxesserver

Added availability to kill server using KeyboardInterrupt (usually CTRL+C). In the master version, the FileChecker thread doesn't stop, this should help it.
(Tested on Windows 10)

Keyboard interruption for BoxesServer

---

boxes/__init__.py
documentation/src/api_existing_parts.rst

Fixes #459 by allowing multiple edge definitions for polygonWall.  Also added function documentation to polygonWall.
The call on line 2710 to _polygonWallExtend may need additional comments since it does not account for multiple edge types.  I'm not entirely sure how to use those to calculate the extents of the shape.
I did spot check the output of console and heart to confirm that this change did not introduce a regression error, but did not attempt multiple variations.  I didn't see any automatic tests, but let me know if there are any e2e or snapshot tests that could be run to confirm behavior.

Add edges to polygonWall

---

boxes/edges.py

grip_percentage is initialized with integer zero value but was not divided by 100 when used.
In this small patch division by 100 is added

Fix processing of grip_percentage parameter

---

setup.py

Python 3.6 reached end of life 2021-12-23.
https://devguide.python.org/versions/
fixes #471

Remove support of EOL Python 3.6

---

documentation/src/install.rst

Python 2.7 was removed. Update documentation.

Doc: remove python 2.7

---

documentation/src/install.rst
documentation/src/usermanual.rst

After some research it seems that `ps2edit` was only used in some releases and `pstoedit` is the common spelling.

Rename `ps2edit` to more common `pstoedit`

---

scripts/boxesserver

As mentioned in  #440 there are a few robots crawling a lot. 
`robots.txt` is not honored by every crawler.
Additionally instruct the crawler not to follow the form and do not index generated data.

Prevent robots from crawling generated data

---

boxes/edges.py

Updates #482 to modern python typing provided for older versions by `from __future__ import annotations`.

Migrate to modern typing

---

scripts/Dockerfile
scripts/boxesserver

commit 0a8dcf0e37880c056d85523cdea97d8c8b166c6e caused the server to *only* respond to localhost by default.  This causes the Docker to not respond properly.  The old server had the default server name as '', but the new one set it to 'localhost'.
This fixes that problem.
In addition, This commit changes the docker file so that you can specify which git repo and commit to check out from.  This allows trivial testing of other forks/branches/users.  The default branch is master and default git repo is Florian's, but you  can now specify new commits and/or branches to clone with
```docker build --build-arg BUILD_BRANCH=<branch-or-commit> --build-arg BUILD_REPO=<my-repo> ...```

Fix boxesserver

---

scripts/boxesserver
static/self.css
static/self.js

I think this search box works reasonably well, and doesn't look horrid.  Maybe best to put the search bar somewhere else?
Here's a screenshot of how it works.  It auto-filters and displays only the generators that contain the search string. 
Should this be a regex search?  Or just a regular search?  Currently, it's just a regular 'if generator name contains substring' kind of search.
As soon as you hit the little 'x' or remove everything from the search box, it reverts back to the original expand/collapse behavior.

Add search box

---

scripts/boxesserver

`onsearch` is non-standard.
`oninput` is standard and robust.
https://caniuse.com/input-event

Fix html: use `oninput` instead of `onsearch`

---

boxes/__init__.py
boxes/generators/gridfinitytraylayout.py
boxes/generators/traylayout.py
scripts/boxesserver
static/self.js

I have created a gridfinity generator from traylayout.  But in the process I added a bit of javascript so that TrayLayout can be done in a single step.  
Here's an example interaction: https://youtu.be/-FVWVScKaLA
Let me know if you think that makes sense and I can fix it up (for example, the layout i always auto-generated right now, even when it shouldn't be, like with 'save to url'.  It should also prompt the user to regenerate if it's been hand modified).
Also, I deleted the special TrayLayout handling code in boxesserver and other places.
If you don't like it for TrayLayout, that's fine -- though I think i'll keep it for my GridfinityTrayLayout (not quite ready, but works great)

Do traylayout in one step

---

boxes/__init__.py
boxes/generators/regularbox.py

Extended the RegularBox generator to be able to use different diameters for the top and bottom polygons. (The side walls have a trapezoid shape in this case.)
If the top and bottom diameters are the same, everything should be the same as before.
Additionally:
+ new "closed" lid type
+ lid type can now be chosen for top and bottom

Allow different top and bottom diameters for RegularBox

---

boxes/generators/rack19box.py

You just have to render any rack19box to see the bug in the rendering of the front panel. This code fixes it. Cheers!

Fixed flanged front wall top edge spacing in rack19box

---

boxes/__init__.py

Fix the CI error. Attribute is set at runtime by the arg parser.

Fix type error: no attribute "thickness"  [attr-defined]

---

setup.py

Add `qrcode==7.3.1` to `setup.py` `install_requires` to match `requirements.txt`.

Add qrcode to setup.py requirements

---

documentation/src/install/windows.rst

backslashes need to be escaped for the windows paths

backslashes not showing in docs

---

.github/workflows/typing.yml
setup.py

Reached end of life 2023-06-27
https://devguide.python.org/versions/

Remove support of EOL Python 3.7

---

.github/workflows/pages.yml
.github/workflows/typing.yml
documentation/src/boxes2rst
documentation/src/boxes2rst.py

* add callable `main` function
* use f-strings
* fix wrong description
* add .py extension to boxes2rst script

Refactor `boxes2rst`

---

boxes/drawing.py

For reproducible output.
Default before Python 3.8.

Change XML attribute order to alphabetical

---

boxes/__init__.py
boxes/gears.py
boxes/generators/alledges.py
boxes/generators/angledbox.py
boxes/generators/atreus21.py
boxes/generators/discrack.py
boxes/generators/dividertray.py
boxes/generators/gear.py
boxes/robot.py
boxes/servos.py
setup.py

* Migrate to f-string
* Remove outdated format specifiers

Migrate to f-string

---

CONTRIBUTING.rst
documentation/src/api_architecture.rst
documentation/src/index.rst
documentation/src/install.rst

docs: rst format

---

boxes/generators/rack19box.py

My laser cutter is pretty big, but not big enough for two 19-inch parts side-by-side. Assuming that most users are going to be in a similar position, this stacks the widest parts vertically (tested with default settings + the 1u settings for my own project + some other random combinations to check for glitches)
(Also I added labels to help me mentally map the code to the parts ^^)
Before:
After:

[rack19box] more laser-cutter-friendly layout

---

boxes/generators/airpurifier.py
boxes/generators/keyholder.py
boxes/generators/pizzashovel.py
boxes/generators/skadis.py

Not marked as executable and should not be executable. Seems leftover from dev.

fix: remove shebang because not an executable

---

.gitattributes
.github/workflows/precommit.yml
.pre-commit-config.yaml
CONTRIBUTING.rst
requirements_dev.txt

Possible configuration for pre-commit as suggested in #600 .
Less extensive version of #601.
Features:
* sorting of `requirements.txt`
* correct execution permissions
* spelling docs-folder
* run `shellcheck`
* run `rstcheck` and other `rst` markup checks
* run `pyupgrade` to avoid old python code style

Add precommit basic

---

boxes/generators/_template.py
boxes/generators/wallrack.py

I still want to tweak this a bit and maybe add some more customisation options, but wanted to create this PR to get some feedback on if the implementation looks ok.
This adds a new generator that creates a wall mounted rack/shelf to store p.e. spices. (at least that is why I created it, because I needed something like that in my kitchen).
Features:
- Customisable height per row
- different top edges for different mounting options
- customisable shelf depth, wall height and also back wall height to add more stability if necessary.
Photo of my Prototype (not suitable to be the example picture. I will add better photos once the PR is done:

Create generator for wall mounted (spice) rack

---

boxes/__init__.py
boxes/drawing.py

Adds option to remove non reproducible data from generated file like creation time.
This is useful if the generated (svg) file is committed to a git or other versioning system. If box generation is not changed it will not trigger a new version.
It also can be used for tests.

feat: add metadata for reproducible generation

---

boxes/generators/shadowbox.py

**Commit 1:**
I made an error with the angles when refactoring, rendering the angle complement calculation ineffective, making them wrong when the angle is not 45 degrees.
**Commit 2:**
I have also added parts to glue the LED strip onto.
**Not yet committed:**
The look of the shadowbox is *greatly* improved by adding a frame around it with nicer wood:
However, this will tend to be of a different thickness than the main construction (e.g. 3mm vs 6mm). I couldn't figure out how to have two different widths apply to finger joints in a single generation, so I don't know how best to do this. To do it myself, I just added them to this generator, ran it twice with different parameters, and manually combined the resulting files as needed.
I suppose I could make a separate "picture frame" …

Shadowbox improvements

---

scripts/Dockerfile

This pull request updates the Dockerfile to optimize the build process and reduce image size. Changes include:
- Using a multi-stage build with a smaller base image (python:3.12-slim) for the builder stage.
- Incorporating Gunicorn to serve the application, enhancing performance and scalability.
- Implementing COPY --from=builder to include only necessary files from the builder stage in the final image.

docker: add gunicorn based docker image

---

boxes/__init__.py
boxes/edges.py
boxes/generators/gridfinitytraylayout.py
boxes/generators/photoframe.py
boxes/walledges.py

Fixes IDE hint that there is a duplicate description which should be more specific. 🙄

fix(docs): typo; unclear description

---

.github/workflows/pages.yml
.github/workflows/precommit.yml
CONTRIBUTING.rst
documentation/src/install/windows.rst
scripts/Dockerfile

Since `pyproject.toml` is available the pip install can be simplified from
> pip install -r requirements.txt
to
> pip install .

feat: use new pip install

---

.github/workflows/pages.yml
.github/workflows/precommit.yml
.pre-commit-config.yaml
boxes/generators/brick_sorter.py
pyproject.toml
tests/test_svg.py

Python 3.8 is eol since 07 Oct 2024. Python 3.13 not added yet, because of behavour change.
Fixes tests by excluding broken generator `console`.

chore(python): require 3.9; drop eol 3.8

---

boxes/generators/roundedregularbox.py

Same fix as in the commit e80ad1c (https://github.com/florianfesti/boxes/commit/e80ad1c42ac500a3ae6cecb0d767f7f0c3ab3109) but for the roundedregularbox generator.

fixed --top parameter default value in roundedregularbox generator

---

boxes/generators/gridfinitytraylayout.py

Commit messages have details.  Changes summarized are:
- Fix confusing help message on webpage that height is "inner height"
- Support defining height in terms of Gridfinity Units (i.e. 7mm per U)
- Support easily making stackable boxes compatible with Gridfinity
- Enable turning off pad generation
- Cut pads with gridfinity compatible radius
- Cut pads with holes for magnets
See https://www.thingiverse.com/thing:6979985 for example

Various Improvements to Gridfinity Tray

---

boxes/generators/gridfinitybase.py
boxes/generators/gridfinitytraylayout.py

- The GridfinityBase can incorrectly split parts in some cases because the split was not accounting for the pad. This was introduced when adding split functionality.
- GridfinityTrayLayout etching of pad locations will write the etching multiple overlapping times when the size of the tray is 1 or 2 grid units in either the x or y direction.

Minor Fixes to GridfinityBase and GridfinityTrayLayout

---

boxes/generators/gridfinitytraylayout.py

The Gridfinity specification establishes that one height unit is 7mm, so a 6U box would be exactly 42mm high.  When a laser cut box sits on a laser cut base, the box wall height is the total height minus the thickness of the material being cut.  When a laser cut box sites on a 3D printed base, the base itself is 4.65mm (per the Gridfinity) specification so the box walls need to be shorter.
This can be seen in the following pictures:
A 6u (42mm) tall tray with stacking header (3.7mm) is a total of 45.7mm either 3d printed or laser.
A 3d printed tray can sit on either a 3d printed base or a laser base and will still be the correct height.  However, a laser cut tray can only sit on a laser cut base and be the correct height.  If a laser cut tray is on a 3d printed base it will sit too high. …

feat: support gridfinitytray compatible with both laser and 3d printed bases
