florianfesti/boxes

examples/generate.sh
Change the generate script to run from the command line, fixing the changes in the parameters.
=> Change the generate script

scripts/boxesserver
=> http -> https

scripts/boxesserver
Some hardening for website.
* activate some xss protections by browser
* disable referrer
Not tested the python script.
Test page:
https://securityheaders.com/?q=https%3A%2F%2Fwww.festi.info%2Fboxes.py%2F&followRedirects=on
=> add security headers for browser

boxes/generators/silverwarebox.py
Make the messurements selectable
=> Parameterize Silverwarebox

boxes/generators/paintbox.py
A simple stackable paintstand, very much inspired by:
https://www.youtube.com/watch?v=6HJarJg1npk
=> Add a generator for paintstands

documentation/src/install.rst
I also have some screenshots which might help Windows users even more. If you like having them included, simply drop a line.
=> Add installation guide for Windows (fixes #83)

scripts/Dockerfile
=> [Docker] clean dnf cache to save space

boxes/svgutil.py
=> link: http -> https

README.rst
update description as on hackaday
=> [doc] remove python 2 #168

po/fr.po
Hello, here is a French translation
=> new FR translation

boxes/generators/eurorackskiff.py
made the distribution on the holes for the rails a little more even
=> Rail holes dist

boxes/generators/keypad.py
=> Keypad support for CPG151101S11 hotplug sockets

po/fr.po
Just a small fix on the french translation
=> Fix #210: Typo on website

scripts/boxesserver
This PR adds a button which modifies the current URL to include the current settings. 
This allows e.g. bookmarking or sharing designs _before_ they are rendered, allowing modifications etc.
=> Add "Save to URL" button

boxes/generators/unevenheightbox.py, scripts/boxesserver
A follow up to my previous PR, adding a simple option to UnevenHeightBox.
=> Add --lid_height in UnevenHeightBox; Add "Save to URL" button

boxes/generators/burntest.py, po/zh_CN.po
fixes #284
note: I am pretty sure about the guessed meaning but it is a guess
there is a small risk that I have broken something with multiline string
How can I regenerate website and view it to check is everything OK? I looked into https://github.com/florianfesti/boxes/blob/master/CONTRIBUTING.rst and have not noticed info about it
=> attempt to make burn test description more newbieproof

boxes/generators/burntest.py, po/zh_CN.po
fixes #288
Probably can be improved further, but I am out of ideas for now.
For images: 
- do you prefer pull request or just posting image on issue tracker?
- Do you prefer to get only images of high quality or is it OK to send also mediocre ones?
=> try to add explanation how burn test works

boxes/generators/two_piece.py
note: I am very inexperienced, this is based on a single test (with 0.05 and 0.15 box) and advice from local expert
both apply to plywood
fixes #298
warning: untested
=> increase play in two piece to 0.15

CONTRIBUTING.rst
at least for me it was not obvious and it seems worth documenting
=> hint for what needs to be run

setup.py
not sure whether this classification has any impact on anything, but it seems deserving to me
=> update status from beta to Production/Stable

boxes/generators/burntest.py
not sure how https://github.com/florianfesti/boxes/blob/master/po/zh_CN.po#L1345 should be modified
=> mention similar ones in burn test

boxes/generators/platonic.py
Rough version with no settings exposed.
I had to create a custom finger generator, to unevenly place leftover space.
I'm generating only positive fingers. I have worry, that they will won't fit together, and negative fingers account for some play, that I'm not sure about.
Inspiration.
Here I compare two generated sides.
=> Add platonic solid generator

static/fonts.css
small performance improvement
https://web.dev/font-display/
=> add font-display:swap

boxes/__init__.py
(codespell found more but then I realized that I am procrastinating, so submitted only what I fixed already)
=> fix some typos with codespell

scripts/boxesserver
=> Remove unreachable code

scripts/boxesserver
* fixed typo `utf8` instead of `utf-8`
* removed charset if image is sent
=> fix wrong encoding header from server

scripts/boxesserver, static/normalize.css, static/self.css
No real functional change, just more "current" standard.
=> Some refactor to the html

boxes/generators/paperbox.py
Second design suggested in #351 for the Paperbox.
@fuddl here is the result for `--x=84 --y=13 --h=85 --design=tuckbox` [paperbox.zip](https://github.com/florianfesti/boxes/files/7776026/paperbox.zip)
Do you have suggestions? For example on the design parameter name, descriptions, or on explanatory sketches?
=> Paperbox: second design suggested in #351

boxes/__init__.py, boxes/drawing.py, boxes/formats.py
This adds native file output support for Lightburn (https://lightburnsoftware.com/) file format. The code is used for creating my projects since about 3 months now, so the most obvious errors have been fixed.
Unfortunately there is no official documentation for the file format of Lightburn, so the implementation relies on reverse engineering of saved files. Furthermore this is not officially supported by Lightburnsoftware (they don't even know this exists).
Thanks
Klaus Steinhammer
PS: as I am new to Github and this is the first time submitting some code this way, please be patient with me.
=> add Lightburn .lbrn2 file format support

scripts/boxesserver
Ability to specify host for running web server. 
e.g. ./boxesserver localhost:8000
This userful for start under nginx. For start boxesserver in VDS with several virtualhost.
=> Add host parameter to boxesserver

documentation/src/usermanual.rst
=> Fix a handful of typos in usermanual.rst

boxes/__init__.py
fixed debug rectangle to be painted with ANNOTATIONS color
=> fixed debug rectangle to be painted with ANNOTATIONS color

boxes/generators/burntest.py
- changed font color to ETCHING, 
- changed font size to depend on tile size, enabling smaller tiles with readable text
=> Reworked text appearance in BurnTest generator

boxes/generators/laptopstand.py
Adding a new generator for a simple laptop stand.  Two triangular pieces fit together to form an X shape on which a laptop can sit.
I haven't yet actually cut a prototype, when I do I'll include a photo in this PR.
In the meantime, any feedback is appreciated :+1:
=> Laptop-stand: create generator

boxes/__init__.py, boxes/edges.py, boxes/generators/alledges.py, boxes/generators/dividertray.py, boxes/generators/storageshelf.py, boxes/generators/typetray.py, boxes/lids.py, documentation/src/api_edges.rst
Added a new edge type (again).
Inspiration came from https://www.thingiverse.com/thing:327393
There is one issue I would need some help:
I need to call the function argparseSections() which is located in __init__.py in edges.py (line 2507). As it is not part of a class, I see no other way as to copy the function to edges.py...
Do you have a better idea? - I guess my Python knowlege is too limited here.
=> Handle edge

requirements.txt
Should be in sync with `setup.py`.
fixes #473
=> Fix missing version in `requirements.txt`

documentation/src/api_burn.rst, documentation/src/api_drawing.rst, documentation/src/api_edges.rst, documentation/src/api_existing_parts.rst, documentation/src/api_navigation.rst, documentation/src/faq.rst, documentation/src/install.rst
=> Fix typos in documentation

boxes/__init__.py, boxes/drawing.py, boxes/edges.py, boxes/gears.py, boxes/generators/agricolainsert.py, boxes/generators/atreus21.py, boxes/generators/coffeecapsulesholder.py, boxes/generators/discrack.py, boxes/generators/dividertray.py, boxes/generators/keyboard.py, boxes/generators/organpipe.py, boxes/generators/paperbox.py, boxes/generators/phoneholder.py, boxes/generators/roundedbox.py, boxes/generators/trafficlight.py, boxes/svgutil.py
Seems to be leftovers from python 2.7 and copy/paste.
=> Remove outdated code

boxes/drawing.py
Change from default 'us-ascii' to universal 'utf-8'.
=> Change SVG encoding

boxes/generators/displayshelf.py
Implement Sloped Sides and Back Wall for DisplayShelf.
Fixes #464
=> DisplayShelf: Implement back and slope

.github/workflows/typing.yml, boxes/__init__.py, boxes/edges.py, boxes/gears.py, boxes/generators/ottobody.py, scripts/boxesserver
Add Github Action to check Python typing hints.
Happy new year 🎆
=> Add typing test

documentation/src/api_architecture.rst, documentation/src/api_arguments.rst, documentation/src/api_burn.rst, documentation/src/api_edges.rst, documentation/src/api_examples.rst, documentation/src/api_navigation.rst, documentation/src/api_parts.rst
Since I needed to actually read the documentation, I figured I'd contribute some small edits here.
Thanks for such complete and excellent docs!
=> Some minor documentation edits

boxes/gears.py, boxes/pulley.py
=> Doc: Change links to https

documentation/src/boxes2rst, scripts/boxes2inkscape, scripts/boxes2pot
=> Fix typo in script command help text

documentation/src/install/windows.rst
Avoid that user install the outdated version.
=> Doc: remove specific Python version

documentation/src/index.html
* disallow indexing the redirect page
* remove unnecessary script type
=> Doc: update redirect html

boxes/__init__.py, boxes/drawing.py, boxes/edges.py, boxes/generators/halfbox.py, boxes/generators/organpipe.py, boxes/generators/trafficlight.py, boxes/generators/traylayout.py, boxes/generators/wallchiselholder.py, boxes/generators/wallslottedholder.py, boxes/pulley.py, boxes/servos.py, documentation/src/boxes2rst, scripts/boxes2inkscape, scripts/boxesserver
Done with `Pyupgrade` and separated into different commits for better traceability.
Basically code style, no function change.
=> Code migration from older python versions

setup.py
Not in the list of valid values https://pypi.python.org/pypi?%3Aaction=list_classifiers
=> Update `classifiers`: remove outdated

boxes/svgutil.py
Changes on `svgutil`:
* code style
* fix string prefix
* migrate to f-string
* add typing
=> Migration/typing `svgutil`

.github/workflows/typing.yml
Files I missed in my first typing pr  #482
=> Add more files to typing test

boxes/edges.py, boxes/generators/agricolainsert.py, boxes/generators/bintray.py, boxes/generators/can_storage.py, boxes/generators/coindisplay.py, boxes/generators/dinrailbox.py, boxes/generators/lamp.py, boxes/generators/notesholder.py, boxes/generators/phoneholder.py, boxes/generators/regularstarbox.py, boxes/generators/rotary.py, boxes/generators/spicesrack.py, boxes/generators/trafficlight.py, boxes/generators/trianglelamp.py, boxes/generators/wallpinrow.py, boxes/servos.py, boxes/walledges.py
Typing and more of feature `edges`.
Fund problem:
Class `FingerJointBase` access `self.settings.*` which is not defined.
=> Type edges

scripts/boxesserver
* Add meta tags for search engine for language detection
* https://www.w3.org/International/questions/qa-html-language-declarations.en
* Refactor dropdown for language selection, only show if other language available
* https://developers.google.com/search/docs/specialty/international/localized-versions#html
=> Improve server

scripts/boxesserver
When an extra window/tab is opened, settings cannot be accidentally lost.
=> change(web): open external link in new tab

po/de.po
Had some minor issues/comments which are now fixed
=> german translation compiles now

scripts/boxesserver
* code style fixes
* Use `format()` or f-string
* add some typing
=> Typing webserver

boxes/generators/displayshelf.py
Added an option to add dividers in the shelves of the display shelf model. I have not yet extensively tested this yet. 
Afterthought:
It would be nice if I could make this from thinner material but the code doesn't seem to (easily) allow multiple thickness (or I'm overlooking something)
Examples, 100x100x100 box, (inside), thickness of 3.62 mm:
=> Added option for dividers in display shelf model

boxes/generators/paintbox.py
I added an additional bottom plate with holes for taller stuff like (modelmaking) paint brushes.
Somehow it wasn't as easy as duplicating the line for the above finger holes. Not sure if I'm missing something or there is a bug.
Swapping these lines below will cause the rectangularHole and the fingerHoles to be rotated 90 degrees.
```python
wall_callbacks = [
lambda: self.rectangularHole(h / 3, (x / 2.0) - t, hh, hx, r=hr),
lambda: self.fingerHolesAt(0, self.canheight / 3, x, 0),
]
```
=> Attempt at adding an additional row to paint storage rack

scripts/boxesserver, static/self.js
* move & refactor JS to static
* add some typing
* move `head` to functions for reusability
* fix wrong separator for `hreflang` value
* fix various html validator errors
=> boxesserver: refactor

boxes/extents.py
Changes
* add types
* lint code
=> extents: add types

boxes/__init__.py, boxes/drawing.py, boxes/qrcode_factory.py, requirements.txt, scripts/Dockerfile, scripts/boxesserver
Maybe a goofy idea, but I like the idea of creating an exact replica of whatever is in my hand.  This pr adds a QR code of the URL (to lightburn output only at the moment)
Downsides: 
- requires new dependencies, but at least doesn't break if they're not installed.
- is this a dumb idea?  maybe.  I like it though :-)
Upside:
- I don't have to fiddle-fart around with guessing parameters to recreate an exact replica of a model I'm currently holding in my hand.
=> Added a QR code generator.  

boxes/generators/cardbox.py
HI :)
Nice project, i wrote a new generator for a deckbox (for Trading Card Game Decks, such as Magic the Gathering).
I have never contributed to any open source project, so please feel free to comment and critizise and also tell me if this is how it works. The generator is based on the existing cardbox, that i rewrote to fit other needs. Mostly, the slider now goes to the side rather than the front.
Cheers 
Manuel
=> New Generator for Deckbox

scripts/boxes, scripts/boxes2inkscape, scripts/boxes2pot, scripts/boxes_proxy.py, scripts/boxesserver
Preparation for `pyproject.toml` entry-point.
=> Refactor scripts to callable main

boxes/__init__.py, boxes/gears.py, boxes/pulley.py
This move makes it easier to use Cartesian points directly.
I tested both the gearbox and rotary generators (with default settings) to ensure that they both still work.
https://github.com/florianfesti/boxes/issues/561
=> Moved 'drawPoints' from gears.py and pulley.py into Boxes main class

po/fr.po
=> fr translation: fix typos

boxes/__init__.py
Fixes https://github.com/florianfesti/boxes/issues/589
=> Fix formatting problem introduced back in bf9925b

CONTRIBUTING.rst
=> docs: remove travis

requirements.txt
=> chore: sort requirements.txt

CONTRIBUTING.rst
Updated wording around ImageMagick in the contribution documentation to make it a tad clearer.
=> Updated wording around ImageMagick

boxes/generators/cardbox.py, boxes/generators/frontpanel.py
Some if-else constructions which can be simplified.
=> chore: simplify return

scripts/boxes
=> fix: help and versioning

boxes/__init__.py, boxes/drawing.py
Creation date should be part of metadata to be equal in all code instances.
* single creation time
* remove trailing spaces of metadata cli and cli_short
=> fix: single creation time

scripts/boxesserver
* escape description for title attribute
* remove trailing slash on void element
fixes #665
edit: Yay devils PR 😈
=> fix(html): escape description

boxes/generators/matrix.py, examples/Matrix.svg, setup.py
Use subprocess for script execution. Solves bug with path splitting.
fixes #691
=> feat(setup): modernize script execution

boxes/generators/gridfinitybase.py
Let's not waste material by generate the pads together with the openings
=> feat: Gridfinite-base add pads

documentation/src/usermanual.rst
=> Edit usermanual.rst

boxes/__init__.py, boxes/edges.py, documentation/src/api_edges.rst, documentation/src/api_parts.rst
Hi,
a few more minor updates to the documentation.
Best,
Simon
PS: I couldn't figure out how `rectangularWall()`'s `ignore_widths` is supposed to work. In the end I didn't need it but a short explanation in the doc string would be nice.
=> Misc documentation improvements

CONTRIBUTING.rst, boxes/scripts/boxesserver.py, docker-compose.yml
Local dev environment can be easily started with a single command `docker compose up`
=> Add Docker Compose file for easier local dev
